steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.social-automation
      - -t
      - gcr.io/$PROJECT_ID/nws-video-generator:latest
      - .
images:
  - gcr.io/$PROJECT_ID/nws-video-generator:latest
